apiVersion: v1
kind: Service
metadata:
  name: nc
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nc
